### ISSUE TITLE
CracFeatureValidator should ensure JDK is 17

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-crac-tests#3]
### Issue description

https://github.com/micronaut-projects/micronaut-crac-tests/blob/master/buildSrc/src/main/java/io/micronaut/crac/feature/CracFeatureValidator.java

**Comment by timyates** [comment]
I originally left this out, as it will not fail with Java 8

The CRaC JDK provided by azul is Java 17, but that's not to say they couldn't (or don't have the appetite to) backport it to earlier versions

Also, Using a non-supporting JDK 17, would pass this test, but still silently not work (as with JDK 8)

**Comment by sdelamo** [comment]
We will move this files to `micronaut-starter` and remove them from this repository. Initially, CRaC will only work for JDK 17. Thus I think we should have it as 17 only and if Azul backport it to older version we can remove that check from the validator.

**Comment by timyates** [comment]
👍
